apiVersion: v2
name: moyn
version: 2.6.6
appVersion: 22.0.3
description: A file sharing server that puts the control and security of your own data back into your hands.
keywords:
- moyn
- storage
- einfach
- sexy
home: https://noxt.de/
icon: https://cdn.rawgit.com/docker-library/docs/defa5ffc7123177acd60ddef6e16bddf694cc35f/nextcloud/logo.svg
dependencies:
  - name: redis
    version: 11.0.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
