apiVersion: v2
name: moyn
version: 2.6.6
appVersion: 22.0.0
description: Eine einfache Cloud für jeden!
keywords:
- moyn
- storage
- einfach
- sexy
home: https://moyn.io
icon: https://cdn.rawgit.com/docker-library/docs/defa5ffc7123177acd60ddef6e16bddf694cc35f/nextcloud/logo.svg
dependencies:
  - name: postgresql
    version: 10.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
